---
- name: first ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: Us-east-1-NV
    instance_type: t2.micro
    image: ami-759bc50a
    region: us-east-1
   
  tasks:
    - name: launch instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
               
