---
- hosts: localhost
  tasks:
  
    - name: common security group for webservers
      ec2_group:
        name: SG_created_by_ansible
        description: Allow HTTP & SSH in and all out
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
